name: Docker Image CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get short hash
      run: |
        echo "SHORT_SHA=${GITHUB_SHA::7}" | tee -a $GITHUB_ENV

    - name: Build and push image with all features
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./mimc-fast/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        cache-from: |
          type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mimc-fast:buildcache
        cache-to: |
          type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mimc-fast:buildcache,mode=max
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/mimc-fast:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/mimc-fast:${{ env.SHORT_SHA }}
